### ISSUE TITLE
Failed to download_reference_data

### ISSUE THREAD

**Issue by demonlj** [borenstein-lab/MIMOSA2shiny#1]
```
 download_reference_data(seq_db = "Sequence variants (ASVs)", target_db = "AGORA genomes and models")
ASV_AGORA.tar.gz试开URL’http://elbo-spice.gs.washington.edu/shiny/MIMOSA2shiny/refData/ASV_AGORA.tar.gz'

Error in download.file(paste0(source_url, file_id), destfile = paste0(save_to,  :
  cannot open URL'http://elbo-spice.gs.washington.edu/shiny/MIMOSA2shiny/refData/ASV_AGORA.tar.gz'
 Warning message:
In download.file(paste0(source_url, file_id), destfile = paste0(save_to,  :
  cannot open URL 'https://elbo-spice.gs.washington.edu/shiny/MIMOSA2shiny/refData/ASV_AGORA.tar.gz': HTTP status was '502 Bad Gateway'
```
would you offer another way to download the reference data?

btw: MIMOSA2 do analysis connection between KEGG metabolomics and taxonomy species, but my data was 16s RNA seqs, which are not reliable at species level. May I just analyze the data at genus level?
thank you!

**Comment by cnoecker** [comment]
Hello,
Thanks for your interest in using MIMOSA2. We have observed some intermittent download connection issues with this function - sometimes the connection fails on the first attempt but succeeds if you repeat the same command. You can also download the same data from the links here: https://borenstein-lab.github.io/MIMOSA2shiny/downloads.html# It is also worth noting that we are in the process of migrating our data and application to a larger server, which will change the URL and probably resolve these issues as well. 

Regarding your second question, MIMOSA2 can use a variety of strategies to map microbiome taxonomic data to reactions and metabolites with as high a level of resolution as possible, which might depend on your data and environment. You can change the minimum similarity threshold required for a 16S sequence variant to be mapped to a metabolic reconstruction with the "simThreshold" parameter. An alternative strategy is to first run [PICRUSt2](https://github.com/picrust/picrust2) on your data to predict KEGG Orthologs for each taxon, and provide the resulting table of inferred KO abundances in each taxa and sample to MIMOSA2.
