### ISSUE TITLE
error running the web app

### ISSUE THREAD

**Issue by XuhangLi** [borenstein-lab/MIMOSA2shiny#11]
Hi, 

I really like the tool (!!!) but I encountered an error when running the web app by ASV input and using KEGG database. The error information is as follows. 

_Error: "panel.spacing" is not a valid theme element name. function (el, elname) { eldef <- .element_tree[[elname]] if (is.null(eldef)) { stop("\"", elname, "\" is not a valid theme element name.") } if (is.null(el)) return() if (eldef$class == "character") { if (!is.character(el) && !is.numeric(el)) stop("Element ", elname, " must be a string or numeric vector.") } else if (eldef$class == "margin") { if (!is.unit(el) && length(el) == 4) stop("Element ", elname, " must be a unit vector of length 4.") } else if (!inherits(el, eldef$class) && !inherits(el, "element_blank")) { stop("Element ", elname, " must be a ", eldef$class, " object.") } invisible() } dots[[1]][[11]] dots[[2]][[11]]_

Could you please let me know if you can tell any clue from this error info? I am sorry I couldn't provide my dataset due to data privacy reasons, but if you need, I can try to reproduce the error with randomized data and share that with you. 

Probably you can immediately tell the problem from the error info, so let's first go with this! Thank you very much!

Hang

**Comment by cnoecker** [comment]
Hi, sorry for the delayed response. Thanks for your interest in MIMOSA2, and for bringing this to our attention! This seems to be a recently introduced package version conflict in generating the taxa contribution plots for each metabolite. It will probably take a few days to fix, but in the meantime you should be able to run and view the results for the initial comparison of community metabolic potential with metabolite abundances by selecting the checkbox at the bottom of the input page for "Skip taxonomic contribution analysis". I'll follow up ASAP when the plotting error is resolved.

**Comment by XuhangLi** [comment]
Great to hear! Thank you very much!

**Comment by XuhangLi** [comment]
> Hi Hang, we were able to resolve this version conflict and the full web application should be working now. Feel free to let us know if you encounter other problems!

Cool! unluckily, it seems another error was triggerred in my test run. 

_Error: Dimensions exceed 50 inches (height and width are specified in 'in' not pixels). If you're sure you want a plot that big, use `limitsize = FALSE`._

I understand that unexpected errors often occur, so please take your time!

Thanks again in advance!

**Comment by cnoecker** [comment]
Hi Hang - That's interesting. Can you tell me how many taxa are in your dataset and which database option you're using?

**Comment by XuhangLi** [comment]
Hi Cecilia, I have 629 input taxa and was using KEGG. I was able run the analysis through other databases locally in R, but I don’t have a KEGG license so have to use the website for that.

Thanks!

From: Cecilia Noecker ***@***.***>
Reply-To: borenstein-lab/MIMOSA2shiny ***@***.***>
Date: Wednesday, January 12, 2022 at 12:35 PM
To: borenstein-lab/MIMOSA2shiny ***@***.***>
Cc: "Li, Xuhang" ***@***.***>, Author ***@***.***>
Subject: Re: [borenstein-lab/MIMOSA2shiny] error running the web app (Issue #11)


Hi Hang - That's interesting. Can you tell me how many taxa are in your dataset and which database option you're using?

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fborenstein-lab%2FMIMOSA2shiny%2Fissues%2F11%23issuecomment-1011290490&data=04%7C01%7CXuhang.Li%40umassmed.edu%7Cf532e4fd3a3643fcbb7c08d9d5f1eb15%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C637776057284877882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MhUBZvTbnKq9o5MeqmFcJR2Syzb4o%2FHHK5ul11oVXSg%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ6DQPPPQ7WIHTDFHMKGW3LUVW3V3ANCNFSM5LRNGFEQ&data=04%7C01%7CXuhang.Li%40umassmed.edu%7Cf532e4fd3a3643fcbb7c08d9d5f1eb15%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C637776057284877882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zCOkAHgKpliOi9OzYPIsA9JdgtR2ME57zu8Z3PhUCZY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CXuhang.Li%40umassmed.edu%7Cf532e4fd3a3643fcbb7c08d9d5f1eb15%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C637776057284877882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=goDMlZIJQ%2BkTqy%2BAcvPkUkJfqDhd1Iq7BXhDB%2FTqYbs%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CXuhang.Li%40umassmed.edu%7Cf532e4fd3a3643fcbb7c08d9d5f1eb15%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C637776057284877882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=G%2B49YltSZI6fjPAQjtVM7bGKZVi3CKq5Ms8bJQyvc4Y%3D&reserved=0>.

**Comment by cnoecker** [comment]
Got it! This error is due to a slight modification that was supposed to improve the display of the color legend when there are many contributing taxa, but apparently triggers an error if the number of taxa (and therefore the size of the legend) gets too large. You could try filtering out some low-abundance or low-prevalence taxa and then the analysis should work, or otherwise we should be able to have a fix for this in the next day or two.

**Comment by XuhangLi** [comment]
Sounds great! Thanks for the explanation!

From: Cecilia Noecker ***@***.***>
Reply-To: borenstein-lab/MIMOSA2shiny ***@***.***>
Date: Wednesday, January 12, 2022 at 12:48 PM
To: borenstein-lab/MIMOSA2shiny ***@***.***>
Cc: "Li, Xuhang" ***@***.***>, Author ***@***.***>
Subject: Re: [borenstein-lab/MIMOSA2shiny] error running the web app (Issue #11)


Got it! This error is due to a slight modification that was supposed to improve the display of the color legend when there are many contributing taxa, but apparently triggers an error if the number of taxa (and therefore the size of the legend) gets too large. You could try filtering out some low-abundance or low-prevalence taxa and then the analysis should work, or otherwise we should be able to have a fix for this in the next day or two.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fborenstein-lab%2FMIMOSA2shiny%2Fissues%2F11%23issuecomment-1011301278&data=04%7C01%7CXuhang.Li%40umassmed.edu%7C42f7d8275c5f46874cfa08d9d5f3caf1%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C637776065328692868%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eKDl3dL0TXCWJidiKto%2FXoswEw4ecD4R3hJnrSvup7M%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ6DQPLZCJI57VWD3C5NBPTUVW5IDANCNFSM5LRNGFEQ&data=04%7C01%7CXuhang.Li%40umassmed.edu%7C42f7d8275c5f46874cfa08d9d5f3caf1%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C637776065328692868%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=H6d4DN%2BH0unF6IoK0gDynTVbsEmDw9U4y0uorYCak%2F0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CXuhang.Li%40umassmed.edu%7C42f7d8275c5f46874cfa08d9d5f3caf1%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C637776065328692868%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2vPSSY5feb%2B4n6cNNNekdBIqmLfFv2pTEBL%2B8KyLsXU%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CXuhang.Li%40umassmed.edu%7C42f7d8275c5f46874cfa08d9d5f3caf1%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C637776065328692868%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YP72%2Ba20DIMbo9Gr14FfCUs82RCW2PI8VLjCTk4KQjQ%3D&reserved=0>.

**Comment by cnoecker** [comment]
Hi Hang - we updated the app to address this error. Please give it a try again and let me know if it doesn't work. The results page will likely take a little bit to load with that number of taxa. Thanks!

**Comment by XuhangLi** [comment]
Yes, it’s working nicely now. Thanks!


From: Cecilia Noecker ***@***.***>
Reply-To: borenstein-lab/MIMOSA2shiny ***@***.***>
Date: Wednesday, January 12, 2022 at 1:40 PM
To: borenstein-lab/MIMOSA2shiny ***@***.***>
Cc: "Li, Xuhang" ***@***.***>, Author ***@***.***>
Subject: Re: [borenstein-lab/MIMOSA2shiny] error running the web app (Issue #11)


Hi Hang - we updated the app to address this error. Please give it a try again and let me know if it doesn't work. The results page will likely take a little bit to load with that number of taxa. Thanks!

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fborenstein-lab%2FMIMOSA2shiny%2Fissues%2F11%23issuecomment-1011343191&data=04%7C01%7CXuhang.Li%40umassmed.edu%7C81a8234efd4e48ae1ac508d9d5fb10a2%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C637776096571679580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=k3GsgEPTYYbgIwoMfbNR65HMZMSUCAXcOfLVh%2BrkOHs%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ6DQPO7PQM6ATK2FTBU2N3UVXDLLANCNFSM5LRNGFEQ&data=04%7C01%7CXuhang.Li%40umassmed.edu%7C81a8234efd4e48ae1ac508d9d5fb10a2%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C637776096571679580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=foMQHdfgvMYARtK7Y88Tj61FXDna66v0sPcZx2Frn10%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CXuhang.Li%40umassmed.edu%7C81a8234efd4e48ae1ac508d9d5fb10a2%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C637776096571679580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cCc%2BqvXSqWmRUrR6ZZWHz3HxJsEapODFZNtDydAzo4s%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CXuhang.Li%40umassmed.edu%7C81a8234efd4e48ae1ac508d9d5fb10a2%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C637776096571679580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pOMDuvLM3C1OyvQ8iCR6GCZmR21JZsAhDLLiRWfUoCo%3D&reserved=0>.
