### ISSUE TITLE
Error occurring when trying to us Mimosa online

### ISSUE THREAD

**Issue by DuyMDinh-Diversigen** [borenstein-lab/MIMOSA2shiny#12]
Hello,

I am hoping to use Mimosa to access the link between our future microbiome and metabolome dataset.  To that end, I have used the provided sample dataset and obtain results without any issues.  Currently, I am using HMP2 microbiome and metabolome data as further tests, but they don't seem to be working properly.  I am getting a lot of the following errors even though it seems that it had ran.

"An error has occurred. Check your logs or contact the app author for clarification."

I have chose both of the following:
Metagenome: Total KO abundances
Metagenome: Taxon-stratified KO abundances (HUMAnN2 or PICRUSt/PICRUSt2) 

then,
PICRUSt KO genomes and KEGG metabolic model

then,
Metabolite names (search for matching ID)

then,
Rank-based estimation

I've tried changing the ID column to KO but that doesn't seem to help.
The files are attached.  Can someone in group comment?

Thank you,
Duy Dinh
[Species_relAB_trans.txt](https://github.com/borenstein-lab/MIMOSA2shiny/files/9245830/Species_relAB_trans.txt)
[transformed_metab_test.txt](https://github.com/borenstein-lab/MIMOSA2shiny/files/9245831/transformed_metab_test.txt)

**Comment by cnoecker** [comment]
Hi Duy,
Thanks for getting in touch and for sharing your data files. Sorry for the uninformative error message. The problem with your files is that the species table contains species abundances, not KEGG Ortholog abundances as is required by MIMOSA2 for the option(s) you selected. MIMOSA2 does not have an option to automatically map species names to metabolic reactions in the format you've provided. You unfortunately have to do a little bit more pre-processing to use MIMOSA2 on your data. 

For metagenomic data, my recommendation would be to run HUMAnN (I know the program lists HUMAnN2 but HUMann3 also works great) on your data and then use the humann_regroup_table function (see their documentation [here](https://github.com/biobakery/humann#humann_regroup_table)) to convert the resulting table of UniRef gene families to KEGG KOs. The stratified table generated by Humann can then be provided to MIMOSA2 with the "Taxon-stratified KO abundances" option. For the HMP2 data, I believe you can download the UniRef tables directly from the data portal and again, use the humann_regroup_table utility in Humann to map them to KEGG KOs. 

You can find more about the input data types required by MIMOSA2 in the documentation here: https://borenstein-lab.github.io/MIMOSA2shiny/input.html

Hope that helps!

**Comment by DuyMDinh-Diversigen** [comment]
Thank you Cecilia.
