### ISSUE TITLE
Web application error

### ISSUE THREAD

**Issue by PhoebeCrossley** [borenstein-lab/MIMOSA2shiny#15]
Hi,

When I open MIMOSA2 on the web application, I get a 404 Not Found error page with the message "The requested URL was not found on this server". 

I've tried using different browsers and a different computer and all say the same. 

Any help would be appreciated. Thank you!

Phoebe

**Comment by cnoecker** [comment]
Hi Phoebe,
Unfortunately we have an ongoing with the web server for this tool. I hope it will be back up soon but I don't have additional information on that at this time. If you want to try running MIMOSA2 locally, you can find some of the databases linked here: 
- ASV_EMBL for use of EMBL_GEMS database with ASV inputs: https://drive.google.com/drive/folders/1iCuiK1DOujAe9TFLW_SVlskqOJUU_quk?usp=share_link
- ASV_AGORA for use of AGORA database with ASV inputs: https://drive.google.com/drive/folders/1HfcOIo1RsLdFgR_zgaNze8kIKpX-n8sd?usp=share_link

You can find more on running MIMOSA2 locally here: https://borenstein-lab.github.io/MIMOSA2shiny/package.html#

I'll follow up when the server is back online. Feel free to get in touch if you have additional questions about running MIMOSA2 locally.

**Comment by cnoecker** [comment]
Hi Phoebe,
Very sorry for the delayed reply. MIMOSA2 is now back up and running if you are still interested in using the web application: elbo-spice.cs.tau.ac.il/shiny/MIMOSA2shiny/
