### ISSUE TITLE
Can not open the page mimosas2 shiny

### ISSUE THREAD

**Issue by CQMUyan** [borenstein-lab/MIMOSA2shiny#17]
hi, I've recently noticed that the MIMOSA2shiny page doesn't open, could you please check if the page is working correctly?

**Comment by cnoecker** [comment]
Hi, it does look like the server is down - thank you for bringing it to my attention. The server is hosted in Tel Aviv and I am not sure when anyone there will be able to look into it, but I will check. In the meantime, you can find information on running MIMOSA2 locally [here](https://borenstein-lab.github.io/MIMOSA2shiny/package.html#), and feel free to ask any questions about that process.

**Comment by CQMUyan** [comment]
Thank you for your prompt response and for looking into the server issue. I appreciate your assistance. I will explore the local option for running MIMOSA2 as suggested. If I have any questions during the process, I'll be sure to reach out. Thanks again for your help!

**Comment by cnoecker** [comment]
Hello, FYI the web application seems to be back online now. Hopefully it will stay that way, but feel free to reopen if you encounter any other issues.

**Comment by Gabderi** [comment]
Hello, I have been trying to use the MIMOSA2shiny page but it says the server is down. Is it an issue on my part or not?
