### ISSUE TITLE
Unable to access web app

### ISSUE THREAD

**Issue by cckeneally** [borenstein-lab/MIMOSA2shiny#19]
Hi,

Thanks for all your hard work on this software. Unfortunately I'm not currently able to access the web app at http://elbo-spice.cs.tau.ac.il/shiny/MIMOSA2shiny/.

**Comment by cnoecker** [comment]
Thanks for reporting this. I would guess that it's a temporary server outage at TAU and will be back online soon, but I'll follow up if I learn otherwise.

**Comment by cckeneally** [comment]
Thank you

In the meantime - is there a workaround for accessing the KEGG database without a license for the FTP server?
I am trying to use the get_kegg_reaction_info(kos_to_rxns_method=="KEGGREST") to build preprocessed networks but get 403 errors.

**Comment by cckeneally** [comment]
The website appears to be back up as of now!
