### ISSUE TITLE
How about a couple of microbes?

### ISSUE THREAD

**Issue by BinhongLiu** [borenstein-lab/MIMOSA2shiny#2]

**Comment by cnoecker** [comment]
Hello, good question. MIMOSA2 can infers the contributions of different microbes to a metabolite based on their ability to directly metabolize that metabolite - our model does not currently account for interactions between microbes, but it does identify when multiple microbes together (potentially via competition or cooperation) appear to be affecting levels of a metabolite. Hope that helps.
