### ISSUE TITLE
Humann2 input

### ISSUE THREAD

**Issue by huananfshi** [borenstein-lab/MIMOSA2shiny#3]
I tried to input HUMANn2 format file but got error message that the format is not correct. Then I tried to. use total KO table but got a message "An error has occurred. Check your logs or contact the app author for clarification."

**Comment by cnoecker** [comment]
Hi,
Thanks for your interest in using MIMOSA2! Did you compare your input files to the examples provided in the documenation? https://borenstein-lab.github.io/MIMOSA2shiny/input.html# If you think your files are formatted correctly but you are still getting errors, please reply with the first few lines of your input data files and a list of the settings you selected for the analysis, so that we can sort out the problem.

**Comment by huananfshi** [comment]
Hi, thank you for the reply. I fixed the formatting. However, it seems something is wrong with my metabolites input. When I just input 2 rows of my metabolites files, it works. However, when I input the whole file, I got the error message
Error: Problem reading files: Item 2 of i is -1 and item 1 is NA. Cannot mix negatives and NA. eval expr env
I double checked my files that there is no NA and I tried input both pre and post log transformed data.
Really appreciate your help!

**Comment by huananfshi** [comment]
> Hi,
> Thanks for your interest in using MIMOSA2! Did you compare your input files to the examples provided in the documenation? https://borenstein-lab.github.io/MIMOSA2shiny/input.html# If you think your files are formatted correctly but you are still getting errors, please reply with the first few lines of your input data files and a list of the settings you selected for the analysis, so that we can sort out the problem.

Hi, thank you for the reply. I fixed the formatting. However, it seems something is wrong with my metabolites input. When I just input 2 rows of my metabolites files, it works. However, when I input the whole file, I got the error message
Error: Problem reading files: Item 2 of i is -1 and item 1 is NA. Cannot mix negatives and NA. eval expr env
I double checked my files that there is no NA and I tried input both pre and post log transformed data.
Really appreciate your help!

**Comment by cnoecker** [comment]
Hi, thanks for the info. Does your metabolite table have any KEGG IDs with special characters or something else that could cause them to be NAs? When processing the metabolite table, MIMOSA2 removes any rows with duplicate KEGG IDs, and something in that process is likely causing the error. The easiest way to resolve the problem might be to pre-process your metabolite table to only have 1 row for each unique KEGG ID and no rows with non-KEGG IDs. Hope that helps!

**Comment by huananfshi** [comment]
> Hi, thanks for the info. Does your metabolite table have any KEGG IDs with special characters or something else that could cause them to be NAs? When processing the metabolite table, MIMOSA2 removes any rows with duplicate KEGG IDs, and something in that process is likely causing the error. The easiest way to resolve the problem might be to pre-process your metabolite table to only have 1 row for each unique KEGG ID and no rows with non-KEGG IDs. Hope that helps!

Thank you for the quick reply. It seems to be the reason. I cleaned the duplicates and now it works.
