### ISSUE TITLE
Problem in reading file on MIMOSA2

### ISSUE THREAD

**Issue by amoltej** [borenstein-lab/MIMOSA2shiny#6]
Hi, 
I am trying to run the MIMOSA2 analysis and getting following error. 

`Error: Problem reading files: Item 2 of i is -14 and item 1 is NA. Cannot mix negatives and NA. eval expr env`

I do not understand this error as I have already checked my input files for `NA`'s . 
What else I shall check?
Thanks in advance.

**Comment by cnoecker** [comment]
Hi,
I apologize for the slow response to this message. This error most likely indicates a problem either in the importing of files or in the initial formatting and filtering of data tables. I would recommend the following: 
- check the formatting of your input files against the examples in the documentation: https://borenstein-lab.github.io/MIMOSA2shiny/input.html#
- check that your data files uploaded fully before you selected "Run MIMOSA"
- check that the database options you've selected match the types of data you're actually providing (e.g. if SILVA database is selected, you are providing a table of SILVA OTUs). 

If you are still encountering this error, you can also share a subset of your data here for us to review what might be going on. 

Hope that helps!

**Comment by amoltej** [comment]
Hi Thanks for reply. 
I tried with my freshly prepared data. following is the subsection of the data that I tried to use for analysis. 
`

KO | GA1_1 | GA1_2 | GA1_3 | GA2_1 | GA3_1 | GA4_1
-- | -- | -- | -- | -- | -- | --
K00001 | 34216.5 | 69363.68 | 68192.59 | 39587 | 54782.83 | 63736.94
K00002 | 19 | 531 | 30 | 18 | 23 | 7
K00003 | 39792.58 | 59737.08 | 61746.04 | 36040.04 | 45928.19 | 51844.28
K00004 | 75 | 83.4 | 183.2 | 39.2 | 17.2 | 11.6
K00005 | 13214.33 | 20767.24 | 20899.04 | 9528.54 | 7508.52 | 7922.95
K00008 | 41085.83 | 46980.01 | 60185.67 | 30090.34 | 27870.16 | 28344.5
K00009 | 8661 | 18933 | 18230 | 5809 | 14209 | 19023
K00010 | 2046.5 | 8240.5 | 4309 | 563 | 619 | 598
K00012 | 50337 | 98812.01 | 95051.92 | 48292 | 59549 | 68004.76
K00013 | 39532.08 | 58432.08 | 61801.79 | 50721.04 | 51849.19 | 51550.03
K00014 | 50751.08 | 78440.58 | 80055.29 | 58470.04 | 56346.19 | 56306.03
K00015 | 189 | 684 | 286 | 144 | 54 | 31
K00016 | 40326.58 | 66586.97 | 68198.07 | 36810.24 | 56620.89 | 67192.37
K00018 | 33830.33 | 55422.34 | 56598.09 | 38922.34 | 33099.82 | 31389.6
K00020 | 8486 | 8713.18 | 10797.34 | 8313 | 12756.83 | 15175.69
K00023 | 711 | 613.67 | 1341.67 | 547 | 1220.33 | 1581.68
K00024 | 29698 | 55189.34 | 55702.5 | 50506 | 45535.67 | 42741.83

`

`

KEGG | GA1_1 | GA1_2 | GA1_3 | GA2_1 | GA3_1 | GA4_1
-- | -- | -- | -- | -- | -- | --
C02502 | -3.07171 | 0.513472 | 0.40169 | 0.516006 | 0.586337 | -0.09613
C01495 | -2.74494 | 0.208509 | 0.005149 | 0.594176 | 0.666417 | 0.106454
C00022 | -2.39107 | -0.03277 | -0.07502 | 1.305825 | 0.984469 | 0.108656
C00256 | -3.63755 | -1.2204 | -0.97961 | 1.20815 | 1.154301 | 0.564609
C00160 | -2.52916 | -0.40029 | -0.67188 | 1.045928 | 0.985405 | 0.32262
C00183 | -3.04849 | -0.81393 | -0.36409 | 1.136728 | 0.788955 | 0.11209
C00041 | -3.55824 | 0.180128 | -0.09803 | 0.67283 | 0.671209 | 0.25825
C00408 | -2.95778 | -0.15526 | 0.054629 | 0.832013 | 0.752239 | -0.11202
C05145 | -3.18254 | -0.31355 | -0.16439 | 0.77766 | 0.835514 | 0.450882
C03711 | -2.58988 | -0.26094 | -0.50881 | 0.475864 | 0.700065 | -0.24306
C00209 | -3.61031 | 0.050686 | -0.56126 | 0.142942 | 0.323948 | -0.47799
C00383 | -3.61263 | 0.040962 | -0.49497 | 0.231367 | 0.313671 | -0.48664
C05984 | -3.18175 | 0.064654 | -0.38086 | 0.382044 | 0.335218 | -0.22589
C00148 | -2.60981 | -0.23867 | -0.40486 | 0.544494 | 0.83527 | -0.03717
C00196 | -2.22107 | -0.17749 | -0.00162 | 0.411491 | 0.584433 | -0.01026

`

is there any issue with this data set?

**Comment by cnoecker** [comment]
Hi,
Those tables look just fine. Since you are provide KO data with no taxa abundances, you should make sure you are selecting "Metagenome: Total KO abundances" for the microbiome data format, and "PICRUSt KO genomes and KEGG metabolic model" for the gene content and metabolic model source. 
If you receive the second error again, it would be great if you could right click on your browser window, select "Inspect Element", and share here if you see any errors or other messages in the "Console" tab.
Let me know if you check those options and still see error messages.

**Comment by amoltej** [comment]
Hi Thanks for reply,

I was doing same thing and I repeated this carefully but I received same error. Following is the messages from the "Console" tab after "inspect elements"

`This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. MIMOSA2shiny
Sending APH request... antiphishing.js:16:108112
Sun Aug 30 2020 20:40:18 GMT+1000 (Australian Eastern Standard Time) [INF]: Connection opened. http://elbo-spice.cs.tau.ac.il/shiny/MIMOSA2shiny/ shiny-server-client.min.js:1:21737
Sun Aug 30 2020 20:40:18 GMT+1000 (Australian Eastern Standard Time) [DBG]: Open channel 0 shiny-server-client.min.js:1:5331
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ jquery.min.js:2:80629
Sun Aug 30 2020 20:40:20 GMT+1000 (Australian Eastern Standard Time) [DBG]: 3 message(s) discarded from buffer shiny-server-client.min.js:1:5331
Sun Aug 30 2020 20:40:29 GMT+1000 (Australian Eastern Standard Time) [DBG]: 1 message(s) discarded from buffer shiny-server-client.min.js:1:5331
Sun Aug 30 2020 20:40:35 GMT+1000 (Australian Eastern Standard Time) [DBG]: 2 message(s) discarded from buffer shiny-server-client.min.js:1:5331
Sun Aug 30 2020 20:41:13 GMT+1000 (Australian Eastern Standard Time) [DBG]: 2 message(s) discarded from buffer shiny-server-client.min.js:1:5331
Sun Aug 30 2020 20:41:42 GMT+1000 (Australian Eastern Standard Time) [DBG]: 2 message(s) discarded from buffer shiny-server-client.min.js:1:5331

​

`

**Comment by amoltej** [comment]
Hi, I have found slightly different message on console when I changed the browser from firefox to vivaldi (chrome based)
`shiny-server-client.min.js:1 Mon Aug 31 2020 15:06:34 GMT+1000 (Australian Eastern Standard Time) [INF]: Connection opened. http://elbo-spice.cs.tau.ac.il/shiny/MIMOSA2shiny/`

`shiny-server-client.min.js:1 Mon Aug 31 2020 15:06:34 GMT+1000 (Australian Eastern Standard Time) [DBG]: Open channel 0`

`jquery.min.js:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js:2
shiny-server-client.min.js:1`

`Mon Aug 31 2020 15:06:37 GMT+1000 (Australian Eastern Standard Time) [DBG]: 3 message(s) discarded from buffer
shiny-server-client.min.js:1 Mon Aug 31 2020 15:07:21 GMT+1000 (Australian Eastern Standard Time) [DBG]: 2 message(s) discarded from buffer
shiny-server-client.min.js:1`

`Mon Aug 31 2020 15:07:26 GMT+1000 (Australian Eastern Standard Time) [DBG]: 1 message(s) discarded from buffer
shiny-server-client.min.js:1 Mon Aug 31 2020 15:07:30 GMT+1000 (Australian Eastern Standard Time) [DBG]: 1 message(s) discarded from buffer
shiny-server-client.min.js:1` 

`Mon Aug 31 2020 15:09:27 GMT+1000 (Australian Eastern Standard Time) [DBG]: 1 message(s) discarded from buffer
shiny-server-client.min.js:1 Mon Aug 31 2020 15:09:30 GMT+1000 (Australian Eastern Standard Time) [DBG]: 3 message(s) discarded from buffer
shiny-server-client.min.js:1` 

`Mon Aug 31 2020 15:09:36 GMT+1000 (Australian Eastern Standard Time) [DBG]: 1 message(s) discarded from buffer
shiny-server-client.min.js:1` 

`Mon Aug 31 2020 15:09:42 GMT+1000 (Australian Eastern Standard Time) [DBG]: 2 message(s) discarded from buffer`

`DevTools failed to load SourceMap: Could not load content for http://elbo-spice.cs.tau.ac.il/shiny/MIMOSA2shiny/crosstalk.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

`/shiny/MIMOSA2shiny/__sockjs__/n=wDxua3rXrRjLHePlXg/963/u9qou4hx/xhr_streaming:1 Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING`

`shiny-server-client.min.js:1 Mon Aug 31 2020 15:11:52 GMT+1000 (Australian Eastern Standard Time) [INF]: Disconnect detected; attempting reconnect`

`sockjs-0.3.4.min.js:27 GET http://elbo-spice.cs.tau.ac.il/shiny/MIMOSA2shiny/__sockjs__/o=wDxua3rXrRjLHePlXg/info net::ERR_CONNECTION_RESET`

`u._start @ sockjs-0.3.4.min.js:27
(anonymous) @ sockjs-0.3.4.min.js:27
setTimeout (async)
c.delay @ sockjs-0.3.4.min.js:27
c.XHRLocalObject @ sockjs-0.3.4.min.js:27
P.doXhr @ sockjs-0.3.4.min.js:27
(anonymous) @ sockjs-0.3.4.min.js:27
setTimeout (async)
c.delay @ sockjs-0.3.4.min.js:27
P @ sockjs-0.3.4.min.js:27
S @ sockjs-0.3.4.min.js:27
y @ sockjs-0.3.4.min.js:27
(anonymous) @ shiny-server-client.min.js:2
open_p @ shiny-server-client.min.js:1
attempt @ shiny-server-client.min.js:2
setTimeout (async)
exports.retryPromise_p @ shiny-server-client.min.js:2
RobustConnection._connect @ shiny-server-client.min.js:1
RobustConnection._handleClose @ shiny-server-client.min.js:1
conn.<computed> @ shiny-server-client.min.js:2
d.dispatchEvent @ sockjs-0.3.4.min.js:27
(anonymous) @ sockjs-0.3.4.min.js:27
setTimeout (async)
c.delay @ sockjs-0.3.4.min.js:27
y._didClose @ sockjs-0.3.4.min.js:27
b.onclose @ sockjs-0.3.4.min.js:27
d.dispatchEvent @ sockjs-0.3.4.min.js:27
c.xo.onfinish @ sockjs-0.3.4.min.js:27
f.emit @ sockjs-0.3.4.min.js:27
g.xhr.onreadystatechange @ sockjs-0.3.4.min.js:27
shiny-server-client.min.js:1 Mon Aug 31 2020 15:12:05 GMT+1000 (Australian Eastern Standard Time) [INF]: Connection restored
shiny-server-client.min.js:1 Mon Aug 31 2020 15:12:05 GMT+1000 (Australian Eastern Standard Time) [DBG]: Discard and continue from message 14`

Hopefully this is helpful

**Comment by cnoecker** [comment]
Hi,
Some of these messages look like they might be due to losing connection with the server. How large are the files you're providing? Have you tested a smaller version of your dataset?

**Comment by amoltej** [comment]
I tried running subset of the data but received same error message

I have attached my part of the test files for your ref

original file size is very small - genomic data - 720kb and metabolomic data - 71kb

[geno_test.txt](https://github.com/borenstein-lab/MIMOSA2shiny/files/5153800/geno_test.txt)
[met_test.txt](https://github.com/borenstein-lab/MIMOSA2shiny/files/5153801/met_test.txt)

Thank you so much for time and help.

**Comment by cnoecker** [comment]
Hi,
Unfortunately, the problem with these test files is that there is no overlap between the metabolites predicted by these KOs and the metabolites in your metabolite dataset, so MIMOSA2 doesn't have any comparisons to analyze. We'll get a better error check for that situation added to the app soon. Does your full dataset include more genes and metabolites? I don't see any problems with the formatting of these files, and the file sizes you've listed also shouldn't be a problem. If you could try again with a slightly larger share of your dataset, that would be helpful.

Thanks for your patience with these issues!

**Comment by amoltej** [comment]
Hi, thanks for all the support, 
But may I know how did you check for the overlap between metabolites and KOs? I tried searching it but was unsuccessful. 

I have attached my original files for your reference
[Geno_data.txt](https://github.com/borenstein-lab/MIMOSA2shiny/files/5178930/Geno_data.txt)
[Met_data.txt](https://github.com/borenstein-lab/MIMOSA2shiny/files/5178931/Met_data.txt)

 with all the metabolites and KOs identified from the analysis. 
Can you please help me find if the data has any overlap? 
Thanks

**Comment by cnoecker** [comment]
Hi,
Thanks again for your patience and for sharing your data. I checked the overlap between metabolites and KOs in the test data by analyzing those test files with a local installation of the MIMOSA R package, which produces more extensive error messages (see https://borenstein-lab.github.io/MIMOSA2shiny/package.html#).
 
However, I tested your full dataset and overlap was not the issue. The error from the full dataset had to do with importing the metabolite data. MIMOSA2 doesn't handle multiple versions of the same compound (i.e. multiple rows of data assigned the same KEGG ID) very well, so it filters any duplicate rows after the first instance of a KEGG ID. There was a small bug in the way it did this that caused a problem with your data (and resulted in that strange error about -14 and NA values). This should be fixed on the web server very shortly, but in the meantime, you should be able to run your data and get results by removing any rows with duplicate KEGG IDs prior to uploading the file.

Hope that helps!

**Comment by cnoecker** [comment]
One follow-up: The package has been updated on the server and you should now be able to successfully analyze your data with the app. Thanks again for the feedback.
