### ISSUE TITLE
Error: An error has occurred. Check your logs or contact the app author for clarification.

### ISSUE THREAD

**Issue by cgj-tang** [borenstein-lab/MIMOSA2shiny#7]
This error pops up when I try to run MIMOSA2 thru the web app.

Microbiome data format
Metagenome: Total KO Abundances

Gene content and metabolic model source
PICRUSt KO genomes and KEGG metabolic model

Compound ID type
KEGG Compound IDs

CMP-Metabolite regression type
Rank-based estimation

[metabolite_data.txt](https://github.com/borenstein-lab/MIMOSA2shiny/files/5974583/metabolite_data.txt)
[metagenome_data.txt](https://github.com/borenstein-lab/MIMOSA2shiny/files/5974585/metagenome_data.txt)

Those are the files I'm trying to process. Any thoughts? Thanks very much for your assistance

**Comment by cnoecker** [comment]
Hi,
Thanks for providing your settings and data file! We inadvertently introduced a small issue with some metagenome files while updating a different part of the code recently. It has now been fixed - please try again to run your analysis.
